sudo: required

services:
  - docker

language: node_js
node_js:
  - "12"

branches:
  only:
    - master

before_script:
  - npm install

script:
  - npm test
  - npm run publish-coverage
  - npm run lint

after_success:
  - bash sprova-server-build.sh